name: FastAPI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install fastapi tensorflow numpy pytest opencv-python httpx uvicorn python-multipart

    - name: Run tests
      run: |
          cd backend
          pwd
          ls
          pytest
